export const CATALOG: { name: string; cat: string; color: string; scopes?: string[] }[] = [
  { name: "Gmail", cat: "Communication", color: "#EA4335", scopes: ["Read emails you choose", "Create drafts", "Send on your behalf (asks first)"] },
  { name: "Slack", cat: "Communication", color: "#4A154B", scopes: ["Post to selected channels", "Read messages in those channels"] },
  { name: "Microsoft Teams", cat: "Communication", color: "#5059C9" },
  { name: "Telegram", cat: "Communication", color: "#229ED9" },
  { name: "WhatsApp", cat: "Communication", color: "#25D366" },
  { name: "HubSpot", cat: "CRM", color: "#FF7A59", scopes: ["Read & write contacts", "Log activities"] },
  { name: "Salesforce", cat: "CRM", color: "#00A1E0" },
  { name: "Apollo", cat: "Data", color: "#1F2A44", scopes: ["Enrich companies & people"] },
  { name: "Google Sheets", cat: "Productivity", color: "#0F9D58", scopes: ["Read & append to sheets you pick"] },
  { name: "Google Drive", cat: "Productivity", color: "#1A73E8", scopes: ["Read files in one folder"] },
  { name: "Google Docs", cat: "Productivity", color: "#4285F4" },
  { name: "Google Calendar", cat: "Productivity", color: "#1967D2" },
  { name: "Notion", cat: "Productivity", color: "#111111", scopes: ["Create pages", "Read selected databases"] },
  { name: "Freshdesk", cat: "Support", color: "#25C16F", scopes: ["Read tickets", "Post replies as drafts"] },
  { name: "Zendesk", cat: "Support", color: "#03363D" },
  { name: "Linear", cat: "Engineering", color: "#5E6AD2" },
  { name: "Jira", cat: "Engineering", color: "#0052CC" },
  { name: "Stripe", cat: "Payments", color: "#635BFF" },
  { name: "Twitter/X", cat: "Communication", color: "#111111" },
  { name: "LinkedIn", cat: "Communication", color: "#0A66C2" },
  { name: "Instantly", cat: "Communication", color: "#2563EB" },
  { name: "Microsoft Excel", cat: "Productivity", color: "#107C41" },
  { name: "Dropbox", cat: "Productivity", color: "#0061FF" },
  { name: "Trello", cat: "Productivity", color: "#0079BF" },
  { name: "Asana", cat: "Productivity", color: "#F06A6A" },
  { name: "Confluence", cat: "Productivity", color: "#1868DB" },
  { name: "GitHub", cat: "Engineering", color: "#24292F" },
  { name: "Arxiv", cat: "Data", color: "#B31B1B" },
];
